version: "3"
services:
  file_manager:
    build: .
    container_name: file_management_cli
    depends_on:
      - mongo
    volumes:
      - .:/app
    stdin_open: true  # Keeps CLI interactive
    tty: true         # Allocates a terminal

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
